[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "package1"
version = "0.1.0"
dependencies = [
  "tornado==6.4.2",
]
requires-python = ">=3.9"
